---
collections:
  - name: ansible.windows
    version: 3.8.0
  - name: microsoft.ad
    version: 1.12.1
  - name: microsoft.mecm
    version: 2.1.0
  - name: ansible.controller
    version: 4.7.8
  - name: infra.aap_configuration
    version: 4.2.0
